import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";

import aa from "../public/img/aa.png";
import code from "../public/img/code.png";
import design from "../public/img/design.png";
import a from "../public/img/a.png";
import b from "../public/img/b.png";
import c from "../public/img/c.png";
import d from "../public/img/d.png";
import e from "../public/img/e.png";
import f from "../public/img/f.png";
import h from "../public/img/h.png";
import i from "../public/img/i.png";
import l from "../public/img/l.png";
import zz from "../public/img/zz.png";
import adf from "../public/img/adf.jpg";
import bbq from "../public/img/bbq.png";
import ffq from "../public/img/ffq.png";
import qfq from "../public/img/qfq.png";
import ai from "../public/img/ai.png";
import consulting from "../public/img/consulting.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Arya Dewanto Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="logo" href="/public/favicon.ico" />
      </Head>
      <main className="bg-yellow px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">My Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1zUFuVeiwigMbPp8YfSwhQ3US5t5fi37O/view?usp=sharing"
                >
                  Portfolio
                </a>
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1VPGBJJKhqLkM8wVSY4aWXi3nBDCaNeVV/view?usp=drive_link"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Arya Dewanto
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Freelance Web Developer.
            </h3>
            <br />
            <div>
              <a
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                href="https://github.com/AryaDewantoY"
              >
                Github
              </a>
              <a
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                href="https://www.linkedin.com/in/arya-dewanto-708a53230/"
              >
                Linkedin
              </a>
            </div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={aa} layout="fill" objectFit="cover" alt="gambar" />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Ulasan</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Halo! Saya seorang web developer yang saat ini menguasai stack
              dalam hal frontend, HTML, CSS, Tilwind kerangka kerja, Bootstrap,
              dan Daisiyui. lalu React Js, Vue Js dan untuk aplikasi seluler di
              React Native. Ke Backend, saya menggunakan Golang stack dengan
              kerangka mux Gorilla di PHP dengan Codeigniter 4 dan Laravel
              kerangka. Dalam hal fitur konsep, saya menggunakan metode OOP dan
              JWT serta arsitektur monolitik. Ke membuat API, saat ini saya
              mengimplementasikan JsonApi dan RestApi. Juga menggunakan MySql
              dan PostgreSql dalam database. Dengan Pengerjaan
              <span className="text-teal-500"> Solo Project </span>
              atau <span className="text-teal-500">Team Project </span>.
            </p>
            <p className="text-md py-2 leading-8 text-bold-800 dark:text-gray-200">
              Berikut Skill, Pengalaman dan .
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="gambar" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">Skill</h3>
              <h4 className="py-4 text-teal-600">Stack</h4>
              <p className="text-gray-800 py-1">Css, Tailwind & Bootstrap</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">React.Js</p>
              <p className="text-gray-800 py-1">Vue.Js</p>
              <p className="text-gray-800 py-1">React Native</p>
              <p className="text-gray-800 py-1">Php - Laravel & Codeigniter</p>
              <p className="text-gray-800 py-1">Golang</p>{" "}
              <p className="text-gray-800 py-1">Mysql</p>
              <p className="text-gray-800 py-1">Postgre SQL</p>
              <p className="text-gray-800 py-1">Json & Rest API</p>
              <p className="text-gray-800 py-1">Google Cloud</p>
              <p className="text-gray-800 py-1">Apigee</p>
              <p className="text-gray-800 py-1">Web Service</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt="gmbar" />
              <br />
              <p className="py-2 mt-5">Experience</p>
              <h4 className="py-4 text-teal-600">
                PT Bringin Sejahtera Makmur
              </h4>
              <p className="text-gray-800 py-1">
                Fullstack Developer April 2023 - April 2024 Contract
              </p>
              <h4 className="py-4 text-teal-600">PT Indosat Tbk</h4>
              <p className="text-gray-800 py-1">
                Dev Ops April 2024 - Present, Partime
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="gambar" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Profil</h3>
              <h4 className="py-4 text-teal-600">Pendidikan</h4>
              <p className="text-gray-800 py-1">
                Universitas Islam Assyafiiah,
                Jurusan: Komunikasi Penyiaran islam, 2020
                GPA: 3.11
              </p>
              <h4 className="py-4 text-teal-600">Kontak</h4>
              <p className="text-gray-800 py-1">Email: Aryadewanto14@gmail.com</p>
              <p className="text-gray-800 py-1">Phone / Whatsapp: 081278201919</p>
            </div>
          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Project yang pernah saya kerjakan, untuk review bisa klik link
              pada image di bawah ini.
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {[
              { link: "https://www.claymorestore.shop/", src: a },

              { link: "https://yahootgame.c1.is/", src: bbq },

              { link: "https://www.agitacakes.com/", src: h },
              {
                link: "https://play.google.com/store/apps/details?id=com.chipmunktopup.id",
                src: adf,
              },
              { link: "https://vouchergame.id/", src: qfq },
              { link: "https://hotelbumiwiyata.com/", src: i },

              { link: "https://wg-mothership.vercel.app/", src: e },

              { link: "https://arya-ai.netlify.app/", src: ai },

              { link: "https://tunebot.org/premium", src: ffq },
              { link: "https://pagestoremasar97.vercel.app/", src: c },
              { link: "https://aryaaaydproject.vercel.app/", src: l },
              { link: "https://kulator.vercel.app/", src: b },
              { link: "https://whatsbotmev.vercel.app/", src: zz },
              { link: "https://todolist-orcin-one.vercel.app/", src: f },
            ].map((item, index) => (
              <div key={index} className="basis-1/3 flex-1">
                <Link href={item.link}>
                  <div className="hover:cursor-pointer flex justify-center items-center">
                    <Image
                      className="rounded-lg object-cover justify-content: auto;"
                      width={"100%"}
                      height={"100%"}
                      layout="responsive"
                      src={item.src}
                      alt="gambar"
                    />
                  </div>
                </Link>
                <br />
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
